# Generated by Django 3.1.6 on 2021-02-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('celular', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[['man', 'Manhã'], ['noi', 'Noite']], default='noi', max_length=3)),
                ('data', models.DateField()),
                ('ultima_alteração', models.DateTimeField(auto_now_add=True)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.pessoa')),
            ],
        ),
    ]
