# Generated by Django 3.1.6 on 2021-02-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escala',
            name='ministerio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='escala.ministerio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ministerio',
            name='funcao',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
