# Generated by Django 3.1.6 on 2021-02-12 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escala.ministerio'),
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=30)),
                ('ministerio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.ministerio')),
            ],
        ),
        migrations.AddField(
            model_name='escala',
            name='funcao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='escala.funcao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='funcao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='escala.funcao'),
            preserve_default=False,
        ),
    ]
