# Generated by Django 3.1.6 on 2021-02-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_auto_20210212_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='ministerio',
        ),
    ]
