# Generated by Django 3.1.6 on 2021-02-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_auto_20210210_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='ministerio',
        ),
    ]
