# Generated by Django 3.1.6 on 2021-02-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_remove_pessoa_ministerio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ministerio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escala.ministerio'),
        ),
        migrations.AlterField(
            model_name='escala',
            name='ministerio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ministerio_pessoa', to='escala.pessoa'),
        ),
    ]
