# Generated by Django 3.1.6 on 2021-02-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0004_auto_20210210_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escala',
            name='ministerio',
        ),
    ]
